# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 068958e9557643f7f10ae22080a4897d
  secret_key: 864e45f267cb0ce7e57b73dda8bb1eaa
  canvas_page_name: railsmagazine
  callback_url: http://www.showcaseideas.com:12002/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: showcase
    public_host: www.showcaseideas.com
    public_port: 12002
    local_port: 3001
    server_alive_interval: 0

test:
  api_key: 068958e9557643f7f10ae22080a4897d
  secret_key: 864e45f267cb0ce7e57b73dda8bb1eaa
  canvas_page_name: railsmagazine
  callback_url: http://www.showcaseideas.com:12001/
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: showcase
    public_host: www.showcaseideas.com
    public_port: 12001
    local_port: 3001
    server_alive_interval: 0

production:
  api_key: 068958e9557643f7f10ae22080a4897d
  secret_key: 864e45f267cb0ce7e57b73dda8bb1eaa
  canvas_page_name: railsmagazine
  callback_url: http://www.showcaseideas.com:12001
  set_asset_host_to_callback_url: true   
  tunnel:
    public_host_username: 
    public_host: www.showcaseideas.com
    public_port: 4007
    local_port: 3001
    server_alive_interval: 0
